### ISSUE TITLE
Unable to run project, getting errors while building project

### ISSUE THREAD

**Issue by AsjadMahmood** [diegomvh/AngularODataEntity#19]
I am getting errors while running the project. Most of the errors are due to angular and angular-odata lib versions. I have installed and tried all different combinations of angular versions like 11,13,14 but none of them seems to resolve my issue. 
In the console the error shows you need to install this/that version but once you install it you get new errors. 

Currently the versions i am using are : 
Angular : 13.3.0
angular-odata: 0.102.6
Node: 16.10.0

Can anyone help me to specify what versions should I be using to run the project successfully. Thanks

<img width="1199" alt="Screenshot 2022-08-23 at 9 01 02 AM" src="https://user-images.githubusercontent.com/38811693/186066853-bc61ed9a-55b4-4ab3-b2ad-2836a859549e.png">

**Comment by diegomvh** [comment]
I recently upgraded to angular 14.
Could you confirm if the problem persists?
Thank you very much for your issue report.

**Comment by AsjadMahmood** [comment]
hey @diegomvh  Thanks for updating. Now it's working correctly with these versions

Angular : 14.1.0
angular-odata: 0.102.6
Node: 16.10.0
