### ISSUE TITLE
Errors When Running the Project

### ISSUE THREAD

**Issue by Bultjer** [diegomvh/AngularODataEntity#27]
Hi,

I attempted to run this project, but encountered over a hundred errors.

Here are the steps I followed:

git clone https://github.com/diegomvh/AngularODataEntity.git
npm install
ng serve

![image](https://github.com/user-attachments/assets/b11692f1-f1aa-4dff-ac6e-98d450c017c8)

However, it seems like a crucial step might be missing, as it fails to resolve the angular-odata dependency.
![image](https://github.com/user-attachments/assets/ed64576d-d739-4126-a05b-37d963a0f4ad)

I would greatly appreciate any guidance on how to resolve this issue.

Thank you!

**Comment by diegomvh** [comment]
Hi @Bultjer,

Thank you for your issue and for pointing out the need for better documentation for the project. I apologize for the outdated state of the example project and any inconvenience this has caused.

I'm pleased to inform you that I have recently updated the project and added a README.md file that includes detailed instructions on how to clone, set up, and build the angular-odata library, as well as how to start the application.
